import { HTMLAttributes, KeyboardEvent } from '../../../../node_modules/react';
export type UseMenuButtonProps = Omit<HTMLAttributes<Element>, 'color'>;
export declare const useMenuButton: (props?: UseMenuButtonProps) => {
    'aria-controls': string;
    'aria-expanded': boolean;
    'aria-haspopup': boolean | "listbox" | "grid" | "menu" | "false" | "true" | "dialog" | "tree" | undefined;
    'data-active': import('../../..').Booleanish;
    opened: boolean;
    id: string;
    ref: import('../../../../node_modules/react').Dispatch<import('../../../../node_modules/react').SetStateAction<HTMLButtonElement | null>>;
    onClick: (event: import('../../../../node_modules/react').MouseEvent<Element, MouseEvent>) => void;
    onKeyDown: (event: KeyboardEvent<Element>) => void;
    children?: import('../../../../node_modules/react').ReactNode;
    className?: string | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoCapitalize?: (string & {}) | "none" | "off" | "on" | "sentences" | "words" | "characters" | undefined;
    autoFocus?: boolean | undefined;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "false" | "true") | undefined;
    enterKeyHint?: "search" | "next" | "enter" | "done" | "go" | "previous" | "send" | undefined;
    hidden?: boolean | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "false" | "true") | undefined;
    style?: import('../../../../node_modules/react').CSSProperties | undefined;
    tabIndex?: number | undefined;
    title?: string | undefined;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: import('../../../../node_modules/react').AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "off" | "on" | undefined;
    inputMode?: "search" | "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "false" | "true") | undefined;
    "aria-autocomplete"?: "both" | "none" | "inline" | "list" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "false" | "true") | undefined;
    "aria-checked"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-current"?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "false" | "true") | undefined;
    "aria-dropeffect"?: "link" | "none" | "copy" | "move" | "execute" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "false" | "true") | undefined;
    "aria-hidden"?: (boolean | "false" | "true") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "false" | "true") | undefined;
    "aria-multiline"?: (boolean | "false" | "true") | undefined;
    "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-readonly"?: (boolean | "false" | "true") | undefined;
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "false" | "true") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "false" | "true") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import('../../../../node_modules/react').ClipboardEventHandler<Element> | undefined;
    onCopyCapture?: import('../../../../node_modules/react').ClipboardEventHandler<Element> | undefined;
    onCut?: import('../../../../node_modules/react').ClipboardEventHandler<Element> | undefined;
    onCutCapture?: import('../../../../node_modules/react').ClipboardEventHandler<Element> | undefined;
    onPaste?: import('../../../../node_modules/react').ClipboardEventHandler<Element> | undefined;
    onPasteCapture?: import('../../../../node_modules/react').ClipboardEventHandler<Element> | undefined;
    onCompositionEnd?: import('../../../../node_modules/react').CompositionEventHandler<Element> | undefined;
    onCompositionEndCapture?: import('../../../../node_modules/react').CompositionEventHandler<Element> | undefined;
    onCompositionStart?: import('../../../../node_modules/react').CompositionEventHandler<Element> | undefined;
    onCompositionStartCapture?: import('../../../../node_modules/react').CompositionEventHandler<Element> | undefined;
    onCompositionUpdate?: import('../../../../node_modules/react').CompositionEventHandler<Element> | undefined;
    onCompositionUpdateCapture?: import('../../../../node_modules/react').CompositionEventHandler<Element> | undefined;
    onFocus?: import('../../../../node_modules/react').FocusEventHandler<Element> | undefined;
    onFocusCapture?: import('../../../../node_modules/react').FocusEventHandler<Element> | undefined;
    onBlur?: import('../../../../node_modules/react').FocusEventHandler<Element> | undefined;
    onBlurCapture?: import('../../../../node_modules/react').FocusEventHandler<Element> | undefined;
    onChange?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onChangeCapture?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onBeforeInput?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onBeforeInputCapture?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onInput?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onInputCapture?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onReset?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onResetCapture?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onSubmit?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onSubmitCapture?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onInvalid?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onInvalidCapture?: import('../../../../node_modules/react').FormEventHandler<Element> | undefined;
    onLoad?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onError?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onErrorCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onKeyDownCapture?: import('../../../../node_modules/react').KeyboardEventHandler<Element> | undefined;
    onKeyPress?: import('../../../../node_modules/react').KeyboardEventHandler<Element> | undefined;
    onKeyPressCapture?: import('../../../../node_modules/react').KeyboardEventHandler<Element> | undefined;
    onKeyUp?: import('../../../../node_modules/react').KeyboardEventHandler<Element> | undefined;
    onKeyUpCapture?: import('../../../../node_modules/react').KeyboardEventHandler<Element> | undefined;
    onAbort?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onAbortCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onCanPlay?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onCanPlayCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onCanPlayThrough?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onCanPlayThroughCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onDurationChange?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onDurationChangeCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onEmptied?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onEmptiedCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onEncrypted?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onEncryptedCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onEnded?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onEndedCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadedData?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadedDataCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadedMetadata?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadedMetadataCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadStart?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onLoadStartCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onPause?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onPauseCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onPlay?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onPlayCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onPlaying?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onPlayingCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onProgress?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onProgressCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onRateChange?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onRateChangeCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onResize?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onResizeCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSeeked?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSeekedCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSeeking?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSeekingCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onStalled?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onStalledCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSuspend?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSuspendCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onTimeUpdate?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onTimeUpdateCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onVolumeChange?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onVolumeChangeCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onWaiting?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onWaitingCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onAuxClick?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onAuxClickCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onClickCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onContextMenu?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onContextMenuCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onDoubleClick?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onDoubleClickCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onDrag?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragEnd?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragEndCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragEnter?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragEnterCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragExit?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragExitCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragLeave?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragLeaveCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragOver?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragOverCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragStart?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDragStartCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDrop?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onDropCapture?: import('../../../../node_modules/react').DragEventHandler<Element> | undefined;
    onMouseDown?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseDownCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseEnter?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseLeave?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseMove?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseMoveCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseOut?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseOutCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseOver?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseOverCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseUp?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onMouseUpCapture?: import('../../../../node_modules/react').MouseEventHandler<Element> | undefined;
    onSelect?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onSelectCapture?: import('../../../../node_modules/react').ReactEventHandler<Element> | undefined;
    onTouchCancel?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchCancelCapture?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchEnd?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchEndCapture?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchMove?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchMoveCapture?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchStart?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onTouchStartCapture?: import('../../../../node_modules/react').TouchEventHandler<Element> | undefined;
    onPointerDown?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerDownCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerMove?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerMoveCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerUp?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerUpCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerCancel?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerCancelCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerEnter?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerLeave?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerOver?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerOverCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerOut?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onPointerOutCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onGotPointerCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onGotPointerCaptureCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onLostPointerCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onLostPointerCaptureCapture?: import('../../../../node_modules/react').PointerEventHandler<Element> | undefined;
    onScroll?: import('../../../../node_modules/react').UIEventHandler<Element> | undefined;
    onScrollCapture?: import('../../../../node_modules/react').UIEventHandler<Element> | undefined;
    onWheel?: import('../../../../node_modules/react').WheelEventHandler<Element> | undefined;
    onWheelCapture?: import('../../../../node_modules/react').WheelEventHandler<Element> | undefined;
    onAnimationStart?: import('../../../../node_modules/react').AnimationEventHandler<Element> | undefined;
    onAnimationStartCapture?: import('../../../../node_modules/react').AnimationEventHandler<Element> | undefined;
    onAnimationEnd?: import('../../../../node_modules/react').AnimationEventHandler<Element> | undefined;
    onAnimationEndCapture?: import('../../../../node_modules/react').AnimationEventHandler<Element> | undefined;
    onAnimationIteration?: import('../../../../node_modules/react').AnimationEventHandler<Element> | undefined;
    onAnimationIterationCapture?: import('../../../../node_modules/react').AnimationEventHandler<Element> | undefined;
    onTransitionEnd?: import('../../../../node_modules/react').TransitionEventHandler<Element> | undefined;
    onTransitionEndCapture?: import('../../../../node_modules/react').TransitionEventHandler<Element> | undefined;
};
